'''
Name : Guessing the Number game.
Created by : Raman Sharma
Language Used : Python 3.9
'''
import random

comp= random.randint(1,100)

user=int(input("Guess A Number Between 1 to 100\n  : "))

count =1
while user>comp: 
    a = int(input("Keep Tying , Please Guess Another Number : "))
    if a!=comp:
        count=count+1
        if(a<comp):
            print(f"    HINT : Enter 'Higher' Number than {a} ")
        elif(a>comp):
            print(f"    HINT : Enter 'Smaller' Number than {a} ")
    else:
        print(f"Congratulations , You guess the correct no. after '{count}' turns.\nThe no. Generated by Computer is : {comp} ")
        break
while user<comp:
    a = int(input("Keep Trying , Please Guess Another Number : "))
    if a!=comp:
        count=count+1
        if(a<comp):
            print(f"    HINT : Enter 'Higher' Number than {a} ")
        elif(a>comp):
            print(f"    HINT : Enter 'Smaller' Number than {a} ")
    else:
        print(f"Congratulations , You guess the correct no. after '{count}' turns.\nThe no. Generated by Computer is : {comp} ")
        break
if user==comp:
    print(f"Congratulations, Your Guessing Game is too strong.\nThe no. Generated by Computer is : {comp}  ")